name: Deploy
on:
  push:
    branches: [ master ]
  
jobs:
  deploy:
    name: Deploy to GH pages
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
 
    - run: |
        mkdir -p output
    
    - name: PanDoc rendering
      uses: docker://pandoc/core:2.9
      with:
        args: --standalone --output=output/concentration.html md/concentration.md
    - run: |
        echo "::set-env name=FILELIST::$(printf '"%s" ' *.md)"
    - uses: docker://pandoc/latex:2.9
      with:
        args: --output=output/concentration.pdf ${{ env.FILELIST }}
    
    - name: to gh-pages
      uses: s0/git-publish-subdir-action@master
      env:
        REPO: self
        BRANCH: gh-pages
        FODLER: output
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload artifact     
      uses: actions/upload-artifact@master
      with:
        name: output
        path: output